name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
#repository: https://github.com/flutter/plugins/tree/main/packages/camera/camera
repository: https://github.com/Aardman/flutter-camera-greenscreen/camera_greenscreen/camera

issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.9.4+35

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.camera
        pluginClass: CameraPlugin
      ios:
        pluginClass: CameraPlugin
      web:
        default_package: camera_web

dependencies: 
#  camera_platform_interface: ^2.1.0
  camera_platform_interface:
    git:
      url: https://github.com/Aardman/flutter-camera-greenscreen
      path: camera_greenscreen/camera_platform_interface
  #camera_web: ^0.2.1 
  camera_web:
    git:
      url: https://github.com/Aardman/flutter-camera-greenscreen
      path: camera_greenscreen/camera_web
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2
  quiver: ^3.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  video_player: ^2.0.0
